# Generated by Django 5.0.14 on 2026-06-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('battle', 'Баттл'), ('casting', 'Кастинг'), ('championship', 'Чемпионат'), ('festival', 'Фестиваль')], max_length=20, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Адрес или «онлайн»', max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(verbose_name='Дедлайн регистрации'),
        ),
    ]
