# Generated by Django 5.0.14 on 2026-06-17 11:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('solo', 'Сольный танцор'), ('team', 'Танцевальная команда'), ('organizer', 'Организатор мероприятий'), ('specialist', 'Специалист (фото/видео/звук)')], default='solo', max_length=15, verbose_name='Тип аккаунта')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Уникальное имя (@username)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('bio', models.TextField(blank=True, verbose_name='О себе (кратко)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Фото профиля')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='users/covers/', verbose_name='Обложка профиля')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='Название организации')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('social_media', models.TextField(blank=True, help_text='Ссылки на социальные сети (каждая с новой строки)', verbose_name='Социальные сети')),
                ('experience_description', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверенный организатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль организатора',
                'verbose_name_plural': 'Профили организаторов',
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('photographer', 'Фотограф'), ('videographer', 'Видеооператор'), ('sound_engineer', 'Звукорежиссер'), ('editor', 'Монтажер'), ('choreographer', 'Хореограф-постановщик'), ('other', 'Другое')], max_length=50, verbose_name='Специализация')),
                ('portfolio_description', models.TextField(blank=True, verbose_name='Описание портфолио')),
                ('price_range', models.CharField(blank=True, max_length=100, verbose_name='Ценовой диапазон')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказов')),
                ('equipment', models.TextField(blank=True, verbose_name='Оборудование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль специалиста',
                'verbose_name_plural': 'Профили специалистов',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название команды')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя (@username)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('dance_styles', models.CharField(blank=True, max_length=300, verbose_name='Стили танцев')),
                ('description', models.TextField(blank=True, verbose_name='Описание команды')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='Логотип команды')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='teams/covers/', verbose_name='Обложка команды')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('is_open_recruitment', models.BooleanField(default=True, verbose_name='Открыт набор')),
                ('max_members', models.PositiveIntegerField(default=20, verbose_name='Максимальное количество участников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('leader', models.OneToOneField(limit_choices_to={'user_type': 'team'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL, verbose_name='Лидер команды')),
            ],
            options={
                'verbose_name': 'Танцевальная команда',
                'verbose_name_plural': 'Танцевальные команды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', 'Капитан'), ('member', 'Участник'), ('choreographer', 'Хореограф')], default='member', max_length=20, verbose_name='Роль в команде')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='accounts.team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команд',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams_joined', through='accounts.TeamMember', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_level', models.CharField(blank=True, choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('professional', 'Профессионал')], max_length=50, verbose_name='Уровень подготовки')),
                ('dance_positions', models.CharField(blank=True, max_length=200, verbose_name='Позиция в танце')),
                ('dance_styles', models.CharField(blank=True, max_length=300, verbose_name='Стили танцев')),
                ('favorite_groups', models.CharField(blank=True, max_length=300, verbose_name='Любимые группы')),
                ('experience_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала занятий танцами')),
                ('bio', models.TextField(blank=True, verbose_name='О себе (подробно)')),
                ('mbti', models.CharField(blank=True, max_length=4, verbose_name='Тип MBTI')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('is_available_for_collab', models.BooleanField(default=True, verbose_name='Доступен для коллабораций')),
                ('social_links', models.JSONField(blank=True, help_text='Формат: {"vk": "ссылка", "telegram": "@username", "instagram": "@username"}', null=True, verbose_name='Ссылки на соцсети')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/photos/', verbose_name='Фото профиля')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='profiles/covers/', verbose_name='Обложка профиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль танцора',
                'verbose_name_plural': 'Профили танцоров',
            },
        ),
    ]
