# Generated by Django 5.0.14 on 2026-06-21 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_team_member_roles(apps, schema_editor):
    TeamMember = apps.get_model('accounts', 'TeamMember')
    TeamMember.objects.filter(role='captain').update(role='leader')
    TeamMember.objects.filter(role='choreographer').update(role='member')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_social_features'),
    ]

    operations = [
        migrations.RunPython(migrate_team_member_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('leader', 'Лидер'), ('member', 'Участник')], default='member', max_length=20, verbose_name='Роль в команде'),
        ),
        migrations.CreateModel(
            name='TeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_applications', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Заявка в команду',
                'verbose_name_plural': 'Заявки в команды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('team_application', 'Заявка в команду'), ('team_added', 'Добавлен в команду')], max_length=30, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.team', verbose_name='Команда')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.teamapplication', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'applicant'), name='unique_pending_team_application'),
        ),
    ]
