# Generated by Django 5.0.14 on 2026-06-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_notifications'),
        ('events', '0004_alter_event_event_type_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team_application', 'Заявка в команду'), ('team_added', 'Добавлен в команду'), ('event_application', 'Заявка на мероприятие')], max_length=30, verbose_name='Тип'),
        ),
    ]
