# Generated by Django 5.0.14 on 2026-06-17 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('upload', ' Загрузка файла'), ('youtube', ' Ссылка YouTube')], default='upload', max_length=10, verbose_name='Источник видео')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='covers/videos/', verbose_name='Видеофайл')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/images/', verbose_name='Обложка')),
                ('youtube_id', models.CharField(blank=True, max_length=20, verbose_name='YouTube Video ID')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Ссылка на YouTube')),
                ('title', models.CharField(max_length=150, verbose_name='Название кавера')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Ссылка на превью')),
                ('duration', models.CharField(blank=True, max_length=10, verbose_name='Длительность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Теги (через запятую)')),
                ('views_kver', models.PositiveIntegerField(default=0, verbose_name='Просмотры на KVER')),
                ('likes_kver', models.PositiveIntegerField(default=0, verbose_name='Лайки на KVER')),
                ('youtube_views', models.PositiveIntegerField(default=0, verbose_name='Просмотры на YouTube')),
                ('youtube_likes', models.PositiveIntegerField(default=0, verbose_name='Лайки на YouTube')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Прошёл модерацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covers', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Видео-кавер',
                'verbose_name_plural': 'Видео-каверы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимно')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Прошел модерацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media_app.covermedia', verbose_name='К каверу')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
