# Generated by Django 5.0.14 on 2026-06-22 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_covermedia_mentioned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='covermedia',
            name='feed_type',
            field=models.CharField(choices=[('cover', 'Кавер'), ('performance', 'Выступление')], default='cover', max_length=20, verbose_name='Тип в ленте'),
        ),
        migrations.CreateModel(
            name='CoverLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='media_app.covermedia', verbose_name='Публикация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.AddConstraint(
            model_name='coverlike',
            constraint=models.UniqueConstraint(fields=('user', 'media'), name='unique_cover_like'),
        ),
    ]
