# Generated by Django 5.0.14 on 2026-06-22 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_alter_comment_options_commentlike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverMediaDailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('view_date', models.DateField(verbose_name='Дата просмотра')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='media_app.covermedia', verbose_name='Публикация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_daily_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дневной просмотр',
                'verbose_name_plural': 'Дневные просмотры',
            },
        ),
        migrations.AddConstraint(
            model_name='covermediadailyview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('media', 'user', 'view_date'), name='unique_cover_daily_view_user'),
        ),
        migrations.AddConstraint(
            model_name='covermediadailyview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('media', 'session_key', 'view_date'), name='unique_cover_daily_view_session'),
        ),
    ]
